// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ivakhnenko Dmitry, Moscow",
            "url": "github.com/ivaahn/ssr",
            "email": "ivahnencko01@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login into account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/v1/students/{student_id}/profile": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "Get student's profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StProfile"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/api/v1/students/{student_id}/works": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "Get student's works",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StWorkPlenty"
                        }
                    }
                }
            }
        },
        "/api/v1/supervisors/{supervisor_id}/profile": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supervisor"
                ],
                "summary": "Get supervisor's profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supervisor ID",
                        "name": "supervisor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SvProfile"
                        }
                    }
                }
            }
        },
        "/api/v1/supervisors/{supervisor_id}/works": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supervisor"
                ],
                "summary": "Get supervisor's works",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supervisor ID",
                        "name": "supervisor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SvWorkPlenty"
                        }
                    }
                }
            }
        },
        "/api/v1/works/{work_id}/supervisors": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "works"
                ],
                "summary": "Get supervisors of the work",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Work ID",
                        "name": "work_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkSvPlenty"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.StProfile": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "photoUrl": {
                    "type": "string"
                },
                "studentCard": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.StWorkPlenty": {
            "type": "object",
            "properties": {
                "works": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StWorkResp"
                    }
                }
            }
        },
        "dto.StWorkResp": {
            "type": "object",
            "properties": {
                "is_started": {
                    "type": "boolean"
                },
                "work": {
                    "$ref": "#/definitions/dto.WorkResp"
                }
            }
        },
        "dto.SubjectResp": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.SvProfile": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "dto.SvWorkPlenty": {
            "type": "object",
            "properties": {
                "works": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SvWorkResp"
                    }
                }
            }
        },
        "dto.SvWorkResp": {
            "type": "object",
            "properties": {
                "is_full": {
                    "type": "boolean"
                },
                "is_head": {
                    "type": "boolean"
                },
                "work": {
                    "$ref": "#/definitions/dto.WorkResp"
                }
            }
        },
        "dto.WorkKindResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.WorkResp": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kind": {
                    "$ref": "#/definitions/dto.WorkKindResp"
                },
                "semester": {
                    "type": "integer"
                },
                "subject": {
                    "$ref": "#/definitions/dto.SubjectResp"
                }
            }
        },
        "dto.WorkSv": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "full": {
                    "type": "boolean"
                },
                "head": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "dto.WorkSvPlenty": {
            "type": "object",
            "properties": {
                "supervisors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.WorkSv"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "http://localhost:8080/api/v1/auth/login"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SSR Application",
	Description:      "Student-Supervisor Relationships",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
