// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ivakhnenko Dmitry, Moscow",
            "url": "github.com/ivaahn/ssr",
            "email": "ivahnencko01@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login into account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserFull email",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UserFull password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/v1/relations/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relation"
                ],
                "summary": "Get relations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Supervisor ID",
                        "name": "supervisor_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RelationPlenty"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relation"
                ],
                "summary": "Create relation",
                "parameters": [
                    {
                        "description": "Relation data",
                        "name": "CreateRelation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RelationCreateReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.RelationCreateResp"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relation"
                ],
                "summary": "Update relation",
                "parameters": [
                    {
                        "description": "Relation data",
                        "name": "CreateRelation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RelationUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RelationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/students/{student_id}/profile": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "Get student's profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Student"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/api/v1/students/{student_id}/works": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "Get student's works",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StudentViewWorkPlenty"
                        }
                    }
                }
            }
        },
        "/api/v1/supervisors/{supervisor_id}/profile": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supervisor"
                ],
                "summary": "Get supervisor's profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supervisor ID",
                        "name": "supervisor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Supervisor"
                        }
                    }
                }
            }
        },
        "/api/v1/supervisors/{supervisor_id}/works": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supervisor"
                ],
                "summary": "Get supervisor's works",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supervisor ID",
                        "name": "supervisor_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SupervisorViewWorkPlenty"
                        }
                    }
                }
            }
        },
        "/api/v1/works/{work_id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "works"
                ],
                "summary": "Get supervisors of the work",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Work ID",
                        "name": "work_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WorkFullResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RelationCreateReq": {
            "type": "object",
            "properties": {
                "student_id": {
                    "type": "integer"
                },
                "supervisor_id": {
                    "type": "integer"
                },
                "work_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RelationCreateResp": {
            "type": "object",
            "properties": {
                "relation_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RelationPlenty": {
            "type": "object",
            "properties": {
                "relations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RelationShortResp"
                    }
                }
            }
        },
        "dto.RelationResp": {
            "type": "object",
            "properties": {
                "relation_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "student": {
                    "$ref": "#/definitions/dto.Student"
                },
                "supervisor": {
                    "$ref": "#/definitions/dto.Supervisor"
                },
                "work": {
                    "$ref": "#/definitions/dto.WorkResp"
                }
            }
        },
        "dto.RelationShortResp": {
            "type": "object",
            "properties": {
                "relation_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "student": {
                    "$ref": "#/definitions/dto.StudentShort"
                },
                "supervisor": {
                    "$ref": "#/definitions/dto.SupervisorShort"
                },
                "work": {
                    "$ref": "#/definitions/dto.WorkShortResp"
                }
            }
        },
        "dto.RelationUpdateReq": {
            "type": "object",
            "properties": {
                "relation_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.Student": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "student_card": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.StudentShort": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.StudentViewWorkPlenty": {
            "type": "object",
            "properties": {
                "works": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StudentViewWorkShortResp"
                    }
                }
            }
        },
        "dto.StudentViewWorkShortResp": {
            "type": "object",
            "properties": {
                "work": {
                    "$ref": "#/definitions/dto.WorkShortResp"
                }
            }
        },
        "dto.SubjectResp": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Supervisor": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.SupervisorShort": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.SupervisorViewWorkPlenty": {
            "type": "object",
            "properties": {
                "works": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SupervisorViewWorkShortResp"
                    }
                }
            }
        },
        "dto.SupervisorViewWorkShortResp": {
            "type": "object",
            "properties": {
                "is_full": {
                    "type": "boolean"
                },
                "is_head": {
                    "type": "boolean"
                },
                "work": {
                    "$ref": "#/definitions/dto.WorkShortResp"
                }
            }
        },
        "dto.WaypointResp": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.WorkFullResp": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kind": {
                    "$ref": "#/definitions/dto.WorkKindResp"
                },
                "semester": {
                    "type": "integer"
                },
                "subject": {
                    "$ref": "#/definitions/dto.SubjectResp"
                },
                "supervisors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.WorkSupervisorShort"
                    }
                },
                "waypoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.WaypointResp"
                    }
                }
            }
        },
        "dto.WorkKindResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.WorkResp": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kind": {
                    "$ref": "#/definitions/dto.WorkKindResp"
                },
                "semester": {
                    "type": "integer"
                },
                "subject": {
                    "$ref": "#/definitions/dto.SubjectResp"
                }
            }
        },
        "dto.WorkShortResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kind": {
                    "$ref": "#/definitions/dto.WorkKindResp"
                },
                "subject": {
                    "$ref": "#/definitions/dto.SubjectResp"
                }
            }
        },
        "dto.WorkSupervisorShort": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "full": {
                    "type": "boolean"
                },
                "head": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "http://localhost:8080/api/v1/auth/login"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SSR Application",
	Description:      "Student-Supervisor Relationships",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
