basePath: /
definitions:
  dto.LoginResponse:
    properties:
      access_token:
        type: string
      role:
        type: string
      token_type:
        type: string
      user_id:
        type: integer
    type: object
  dto.RelationCreateReq:
    properties:
      student_id:
        type: integer
      supervisor_id:
        type: integer
      work_id:
        type: integer
    type: object
  dto.RelationCreateResp:
    properties:
      relation_id:
        type: integer
    type: object
  dto.RelationPlenty:
    properties:
      relations:
        items:
          $ref: '#/definitions/dto.RelationShortResp'
        type: array
    type: object
  dto.RelationResp:
    properties:
      relation_id:
        type: integer
      status:
        type: string
      student:
        $ref: '#/definitions/dto.Student'
      supervisor:
        $ref: '#/definitions/dto.Supervisor'
      work:
        $ref: '#/definitions/dto.WorkResp'
    type: object
  dto.RelationShortResp:
    properties:
      relation_id:
        type: integer
      status:
        type: string
      student:
        $ref: '#/definitions/dto.StudentShort'
      supervisor:
        $ref: '#/definitions/dto.SupervisorShort'
      work:
        $ref: '#/definitions/dto.WorkShortResp'
    type: object
  dto.RelationUpdateReq:
    properties:
      relation_id:
        type: integer
      status:
        type: string
    type: object
  dto.Student:
    properties:
      department:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      photo_url:
        type: string
      student_card:
        type: string
      user_id:
        type: integer
      year:
        type: integer
    type: object
  dto.StudentShort:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      user_id:
        type: integer
    type: object
  dto.StudentViewWorkPlenty:
    properties:
      works:
        items:
          $ref: '#/definitions/dto.StudentViewWorkShortResp'
        type: array
    type: object
  dto.StudentViewWorkShortResp:
    properties:
      work:
        $ref: '#/definitions/dto.WorkShortResp'
    type: object
  dto.SubjectResp:
    properties:
      department:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  dto.Supervisor:
    properties:
      about:
        type: string
      birthdate:
        type: string
      department:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      photo_url:
        type: string
      user_id:
        type: integer
    type: object
  dto.SupervisorShort:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      user_id:
        type: integer
    type: object
  dto.SupervisorViewWorkPlenty:
    properties:
      works:
        items:
          $ref: '#/definitions/dto.SupervisorViewWorkShortResp'
        type: array
    type: object
  dto.SupervisorViewWorkShortResp:
    properties:
      is_full:
        type: boolean
      is_head:
        type: boolean
      work:
        $ref: '#/definitions/dto.WorkShortResp'
    type: object
  dto.WaypointResp:
    properties:
      deadline:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
  dto.WorkFullResp:
    properties:
      description:
        type: string
      id:
        type: integer
      kind:
        $ref: '#/definitions/dto.WorkKindResp'
      semester:
        type: integer
      subject:
        $ref: '#/definitions/dto.SubjectResp'
      supervisors:
        items:
          $ref: '#/definitions/dto.WorkSupervisorShort'
        type: array
      waypoints:
        items:
          $ref: '#/definitions/dto.WaypointResp'
        type: array
    type: object
  dto.WorkKindResp:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  dto.WorkResp:
    properties:
      description:
        type: string
      id:
        type: integer
      kind:
        $ref: '#/definitions/dto.WorkKindResp'
      semester:
        type: integer
      subject:
        $ref: '#/definitions/dto.SubjectResp'
    type: object
  dto.WorkShortResp:
    properties:
      id:
        type: integer
      kind:
        $ref: '#/definitions/dto.WorkKindResp'
      subject:
        $ref: '#/definitions/dto.SubjectResp'
    type: object
  dto.WorkSupervisorShort:
    properties:
      first_name:
        type: string
      full:
        type: boolean
      head:
        type: boolean
      last_name:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: ivahnencko01@gmail.com
    name: Ivakhnenko Dmitry, Moscow
    url: github.com/ivaahn/ssr
  description: Student-Supervisor Relationships
  title: SSR Application
  version: 0.1.0
paths:
  /api/auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: UserFull email
        in: formData
        name: username
        required: true
        type: string
      - description: UserFull password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Login into account
      tags:
      - auth
  /api/v1/relations/:
    get:
      parameters:
      - description: Student ID
        in: query
        name: student_id
        type: integer
      - description: Supervisor ID
        in: query
        name: supervisor_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RelationPlenty'
        "404":
          description: Not Found
      security:
      - OAuth2Password: []
      summary: Get relations
      tags:
      - relation
    patch:
      consumes:
      - application/json
      parameters:
      - description: Relation data
        in: body
        name: CreateRelation
        required: true
        schema:
          $ref: '#/definitions/dto.RelationUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RelationResp'
      security:
      - OAuth2Password: []
      summary: Update relation
      tags:
      - relation
    post:
      consumes:
      - application/json
      parameters:
      - description: Relation data
        in: body
        name: CreateRelation
        required: true
        schema:
          $ref: '#/definitions/dto.RelationCreateReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RelationCreateResp'
      security:
      - OAuth2Password: []
      summary: Create relation
      tags:
      - relation
  /api/v1/students/{student_id}/profile:
    get:
      parameters:
      - description: Student ID
        in: path
        name: student_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Student'
        "404":
          description: Not Found
      security:
      - OAuth2Password: []
      summary: Get student's profile
      tags:
      - student
  /api/v1/students/{student_id}/works:
    get:
      parameters:
      - description: Student ID
        in: path
        name: student_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StudentViewWorkPlenty'
      security:
      - OAuth2Password: []
      summary: Get student's works
      tags:
      - student
  /api/v1/supervisors/{supervisor_id}/profile:
    get:
      parameters:
      - description: Supervisor ID
        in: path
        name: supervisor_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Supervisor'
      security:
      - OAuth2Password: []
      summary: Get supervisor's profile
      tags:
      - supervisor
  /api/v1/supervisors/{supervisor_id}/works:
    get:
      parameters:
      - description: Supervisor ID
        in: path
        name: supervisor_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SupervisorViewWorkPlenty'
      security:
      - OAuth2Password: []
      summary: Get supervisor's works
      tags:
      - supervisor
  /api/v1/works/{work_id}:
    get:
      parameters:
      - description: Work ID
        in: path
        name: work_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.WorkFullResp'
      security:
      - OAuth2Password: []
      summary: Get supervisors of the work
      tags:
      - works
schemes:
- http
securityDefinitions:
  OAuth2Password:
    flow: password
    tokenUrl: http://localhost:8080/api/v1/auth/login
    type: oauth2
swagger: "2.0"
