version: "3"


services:
  app:
#    build:
#      dockerfile: deploy/Dockerfile
#      context: ..
    image: ivaaahn/ssr:0.1.2
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - migrate
    restart: unless-stopped

  migrate:
#    build:
#      dockerfile: deploy/Dockerfile.migrate
#      context: ..
    image: ivaaahn/go-migrate:0.1.0
    container_name: migrate
    environment:
      PG_USER: ssradmin
      PG_PSWD: ssradmin
      PG_DB: ssr
      PG_HOST: pg:5432
      WAIT_HOSTS: pg:5432
    volumes:
      - ../migrations:/migrations
    depends_on:
      - pg

  pg:
    image: postgres:alpine
    container_name: pg
    expose:
      - 5432
    environment:
      POSTGRES_DB: ssr
      POSTGRES_USER: ssradmin
      POSTGRES_PASSWORD: ssradmin
      PGDATA: "/data/lib/postgresql/data/pgdata"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data_volume:
