app:
  name: 'ssr'
  version: '0.1.0'

http:
  port: ':8080'

logger:
  log_level: 'debug'


postgres:
  dsn: 'postgres://user:password@host:port/db'

auth:
  token_exp: 10
  signing_key: 'super-secret'