@startuml

namespace Controller {
    class Auth {
        - auth_service: IAuthService
        + Login(),
        + Logout(),
    }

    class Supervisor {
        - work_service: WorkService
        - profile_service: ProfileService

        + GetProfile()
        + GetWorks()
    }

    class Student {
        - work_service: WorkService
        - profile_service: ProfileService

        + GetProfile()
        + GetWorks()
    }

    class Work {
        - work_service: WorkService

        + Get()
    }

}

namespace Service {
    class Auth {
        - userRepo: UserRepo
        + Logout()
        + Login()
    }

    class Profile {
        - studentRepo: StudentRepo
        - supervisorRepo: SupervisorRepo
        + GetStudentProfile()
        + GetSupervisorProfile()
    }

    class Relation {
        - relationRepo WorkRepo
        + Get()
        + GetPlenty()
        + Create()
        + Update()
    }

    class Work {
	    - workRepo: WorkRepo
	    - relationRepo: RelationRepo
	    - stRepo:   StudentRepo
	    - svRepo:   SupervisorRepo
	    - waypointRepo: WaypointRepo
        + Get()
        + GetPlentyByStudent()
        + GetPlentyBySupervisor()
    }
}

namespace Repository {
    class User {
        + GetByEmail()
        + GetByID()
        + Create()
        + Update()
    }

    class Student {
        + GetShort()
        + Get()
        + Update()
    }

    class Supervisor {
        + GetShort()
        + Get()
        + GetPlentyByWork()
        + Update()
    }

    class Relation {
        + Get()
        + GetPlentyByStudent()
        + GetPlentyBySupervisor()
        + Update()
    }

    class WorkRepo {
        + Get()
        + GetPlentyByStudent()
        + GetPlentyBySupervisor()
    }

    class Waypoint {
        + GetPlenty()
    }
}

@enduml